# Generated by Django 5.2.3 on 2025-07-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicationproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicationproduct',
            name='npc_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_chapter_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_chapter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_chemical_substance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_paragraph_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_paragraph_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_presentation_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_section_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_section_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='bnf_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnfhierarchy',
            name='valid_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationproduct',
            name='bnf_code_15digit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medication_products_bnf', to='medications.bnfhierarchy'),
        ),
        migrations.AlterField(
            model_name='medicationproduct',
            name='chemical_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medication_products_chemical', to='medications.chemicalcomposition', to_field='chemical_name'),
        ),
        migrations.AlterField(
            model_name='medicationproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
