# Generated by Django 5.2.3 on 2025-07-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medicationproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationpricinghistory',
            name='price_change_measure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
