# Generated by Django 5.2.3 on 2025-07-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medicationpricinghistory_price_change_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationproduct',
            name='cost_effectiveness_status',
        ),
        migrations.DeleteModel(
            name='CostEffectivenessAppraisal',
        ),
    ]
